// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: proto/rag-tools.proto

package rag_tools

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarkdownChunkerService_ChunkMarkdown_FullMethodName = "/rag_tools.MarkdownChunkerService/ChunkMarkdown"
)

// MarkdownChunkerServiceClient is the client API for MarkdownChunkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarkdownChunkerServiceClient interface {
	ChunkMarkdown(ctx context.Context, in *ChunkMarkdownRequest, opts ...grpc.CallOption) (*ChunkMarkdownResponse, error)
}

type markdownChunkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarkdownChunkerServiceClient(cc grpc.ClientConnInterface) MarkdownChunkerServiceClient {
	return &markdownChunkerServiceClient{cc}
}

func (c *markdownChunkerServiceClient) ChunkMarkdown(ctx context.Context, in *ChunkMarkdownRequest, opts ...grpc.CallOption) (*ChunkMarkdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkMarkdownResponse)
	err := c.cc.Invoke(ctx, MarkdownChunkerService_ChunkMarkdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarkdownChunkerServiceServer is the server API for MarkdownChunkerService service.
// All implementations must embed UnimplementedMarkdownChunkerServiceServer
// for forward compatibility.
type MarkdownChunkerServiceServer interface {
	ChunkMarkdown(context.Context, *ChunkMarkdownRequest) (*ChunkMarkdownResponse, error)
	mustEmbedUnimplementedMarkdownChunkerServiceServer()
}

// UnimplementedMarkdownChunkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarkdownChunkerServiceServer struct{}

func (UnimplementedMarkdownChunkerServiceServer) ChunkMarkdown(context.Context, *ChunkMarkdownRequest) (*ChunkMarkdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChunkMarkdown not implemented")
}
func (UnimplementedMarkdownChunkerServiceServer) mustEmbedUnimplementedMarkdownChunkerServiceServer() {
}
func (UnimplementedMarkdownChunkerServiceServer) testEmbeddedByValue() {}

// UnsafeMarkdownChunkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarkdownChunkerServiceServer will
// result in compilation errors.
type UnsafeMarkdownChunkerServiceServer interface {
	mustEmbedUnimplementedMarkdownChunkerServiceServer()
}

func RegisterMarkdownChunkerServiceServer(s grpc.ServiceRegistrar, srv MarkdownChunkerServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarkdownChunkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarkdownChunkerService_ServiceDesc, srv)
}

func _MarkdownChunkerService_ChunkMarkdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkMarkdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkdownChunkerServiceServer).ChunkMarkdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkdownChunkerService_ChunkMarkdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkdownChunkerServiceServer).ChunkMarkdown(ctx, req.(*ChunkMarkdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarkdownChunkerService_ServiceDesc is the grpc.ServiceDesc for MarkdownChunkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarkdownChunkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag_tools.MarkdownChunkerService",
	HandlerType: (*MarkdownChunkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChunkMarkdown",
			Handler:    _MarkdownChunkerService_ChunkMarkdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rag-tools.proto",
}
