
create extension if not exists "vector" with schema "public" version '0.8.0';

drop index if exists "public"."idx_chunks_text";

drop index if exists "public"."idx_vector_embedding";

create table "public"."embeddings" (
    "id" bigint generated by default as identity not null,
    "chunk_id" integer not null,
    "model" text not null default 'gemini-embedding-exp-03-07'::text,
    "embedding" vector not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."chunks" drop column "chunk_markdown";

alter table "public"."chunks" drop column "chunk_text";

alter table "public"."chunks" add column "jsonb_embedding" jsonb;

alter table "public"."chunks" add column "metadata" json not null;

alter table "public"."chunks" add column "text" text not null;

alter table "public"."chunks" alter column "vector_embedding" set data type vector(3072) using "vector_embedding"::vector(3072);

alter table "public"."pages" alter column "processed_at" drop default;

CREATE UNIQUE INDEX embeddings_pkey ON public.embeddings USING btree (id);

CREATE INDEX idx_chunks_text ON public.chunks USING gin (to_tsvector('english'::regconfig, text));

CREATE INDEX idx_vector_embedding ON public.chunks USING gin (jsonb_embedding);

alter table "public"."embeddings" add constraint "embeddings_pkey" PRIMARY KEY using index "embeddings_pkey";

alter table "public"."embeddings" add constraint "embeddings_chunk_id_fkey" FOREIGN KEY (chunk_id) REFERENCES chunks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."embeddings" validate constraint "embeddings_chunk_id_fkey";

grant delete on table "public"."embeddings" to "anon";

grant insert on table "public"."embeddings" to "anon";

grant references on table "public"."embeddings" to "anon";

grant select on table "public"."embeddings" to "anon";

grant trigger on table "public"."embeddings" to "anon";

grant truncate on table "public"."embeddings" to "anon";

grant update on table "public"."embeddings" to "anon";

grant delete on table "public"."embeddings" to "authenticated";

grant insert on table "public"."embeddings" to "authenticated";

grant references on table "public"."embeddings" to "authenticated";

grant select on table "public"."embeddings" to "authenticated";

grant trigger on table "public"."embeddings" to "authenticated";

grant truncate on table "public"."embeddings" to "authenticated";

grant update on table "public"."embeddings" to "authenticated";

grant delete on table "public"."embeddings" to "service_role";

grant insert on table "public"."embeddings" to "service_role";

grant references on table "public"."embeddings" to "service_role";

grant select on table "public"."embeddings" to "service_role";

grant trigger on table "public"."embeddings" to "service_role";

grant truncate on table "public"."embeddings" to "service_role";

grant update on table "public"."embeddings" to "service_role";