# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import markdown_chunker_pb2 as markdown__chunker__pb2


class MarkdownChunkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChunkMarkdown = channel.unary_unary(
                '/rag_tools.MarkdownChunkerService/ChunkMarkdown',
                request_serializer=markdown__chunker__pb2.ChunkMarkdownRequest.SerializeToString,
                response_deserializer=markdown__chunker__pb2.ChunkMarkdownResponse.FromString,
                )


class MarkdownChunkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChunkMarkdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarkdownChunkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChunkMarkdown': grpc.unary_unary_rpc_method_handler(
                    servicer.ChunkMarkdown,
                    request_deserializer=markdown__chunker__pb2.ChunkMarkdownRequest.FromString,
                    response_serializer=markdown__chunker__pb2.ChunkMarkdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag_tools.MarkdownChunkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarkdownChunkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChunkMarkdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rag_tools.MarkdownChunkerService/ChunkMarkdown',
            markdown__chunker__pb2.ChunkMarkdownRequest.SerializeToString,
            markdown__chunker__pb2.ChunkMarkdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
