# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: markdown_chunker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16markdown_chunker.proto\x12\trag_tools\"L\n\x14\x43hunkMarkdownRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x12\n\nchunk_size\x18\x02 \x01(\x05\x12\x0f\n\x07overlap\x18\x03 \x01(\x05\"\'\n\x15\x43hunkMarkdownResponse\x12\x0e\n\x06\x63hunks\x18\x01 \x03(\t2n\n\x16MarkdownChunkerService\x12T\n\rChunkMarkdown\x12\x1f.rag_tools.ChunkMarkdownRequest\x1a .rag_tools.ChunkMarkdownResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'markdown_chunker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHUNKMARKDOWNREQUEST']._serialized_start=37
  _globals['_CHUNKMARKDOWNREQUEST']._serialized_end=113
  _globals['_CHUNKMARKDOWNRESPONSE']._serialized_start=115
  _globals['_CHUNKMARKDOWNRESPONSE']._serialized_end=154
  _globals['_MARKDOWNCHUNKERSERVICE']._serialized_start=156
  _globals['_MARKDOWNCHUNKERSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
